- name: Download app package
  get_url:
    url: "{{ sg_loader_url }}"
    dest: "{{ sg_tmpdir.path }}/"
  tags:
    - sourceguardian
    - sg_loader
    - sg-update

- name: Install App package
  unarchive:
    src: "{{ sg_tmpdir.path }}/{{ sg_loader_archive }}"
    dest: "{{ sg_datadir }}"
    remote_src: yes
  tags:
    - sourceguardian
    - sg_loader
    - sg-update
